runmode: debug                 # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: file,stdout        #输出位置，有两个可选项 —— file 和 stdout。选 择 file 会将⽇志记录到 logger_file 指定的⽇志⽂件中，选 择 stdout 会将⽇志输出到标准输出，当然也可以两者同时选 择
  logger_level: DEBUG         #⽇志级别，DEBUG、INFO、WARN、 ERROR、FATAL
  logger_file: log/apiserver.log #⽇志⽂件
  log_format_text: false      #⽇志的输出格式，JSON 或者 plaintext，true 会输出成⾮ JSON 格式，false 会输出成 JSON 格式
  rollingPolicy: daily        #rotate 依据，可选的有 daily 和 size。如 果选 daily 则根据天进⾏转存，如果是 size 则根据⼤⼩进⾏转 存
  log_rotate_date: 1          #rotate 转存时间，配 合rollingPolicy: daily 使⽤
  log_rotate_size: 1          #rotate 转存⼤⼩，配合 rollingPolicy: size 使⽤
  log_backup_count: 7         #当⽇志⽂件达到转存标准时，log 系统 会将该⽇志⽂件进⾏压缩备份，这⾥指定了备份⽂件的最⼤个数
  jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: api
  password: 123456
docker_db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: api
  password: 123456



